### ISSUE TITLE
Problem getting statistics

### ISSUE THREAD

**Issue by sterni1971** [PySlurm/pyslurm#101]
After update I see the following problem

>>> sdiag = pyslurm.statistics().get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 4301, in pyslurm.pyslurm.statistics.get (pyslurm/pyslurm.c:54099)
  File "pyslurm/pyslurm.pyx", line 4356, in pyslurm.pyslurm.statistics.get (pyslurm/pyslurm.c:53493)
  File "pyslurm/pyslurm.pyx", line 4611, in pyslurm.pyslurm.statistics.__rpc_num2string (pyslurm/pyslurm.c:54599)
KeyError: 2049

#### Details

* Slurm Version: slurm-17.11.3-2.el7.x86_64
* Python Version: 2.7.5
* Cython Version:
* PySlurm Branch: python-pyslurm-17.11.2-1.x86_64
* Linux Distribution: Centos 7.4

#### Issue
My monitor script throws an exception "2049", when I try to get the statistics

**Comment by giovtorres** [comment]
Hi @sterni1971, I fell behind one release.  I'm pretty sure there were some updates to the __rpc_num2string dictionary, which is generating that error.  I'm building the latest docker images now and I should have pyslurm updated for 17.11.3 by tomorrow.  Thanks!

**Comment by giovtorres** [comment]
Ok, update and give it a try now.

**Comment by giovtorres** [comment]
Hi @sterni1971 , were you able to confirm this is working now?

**Comment by giovtorres** [comment]
I'm closing this issue.  Please re-open if it's still not working.

**Comment by sterni1971** [comment]
sorry for the late reply. everything works again.
thanks for fixing it
