### ISSUE TITLE
/usr/bin/python setup.py sdist and /usr/bin/python setup.py bdist_rpm extremely incomplete and wrong.

### ISSUE THREAD

**Issue by olahaye74** [PySlurm/pyslurm#105]
#### Details

* Slurm Version: slurm-devel-17.11.5-1.el7
* Python Version: python-2.5.7-58.el7
* Cython Version: Cython-0.19-5.el7
* PySlurm Branch: master
* Linux Distribution: CentOS-7 (also on Fedora-27 and maybe CentOS-6)

#### Issues
1/ rpm is incomplete and wrong.
  - %description is way too long and doesn't describe pyslurm (it is the full content of README.rst and has nothing to do with what the package is (why lidting deps or build instruction there?))
  - no %check section while tests can be run
  - doc missing
  - man.1 missing
  - examples missing
  - doc/conf.py not included in anyway (and need update to 17.11.0.7 as it still reports as 17.02.0) 

2/ the tarball and the rpm lack many files:
  - doc dir is missing
  - examples dir is missing
  - tests dir is missing
  - CONTRIBUTORS, COPYING, THANKS are missing

Maybe some missing entries in the setup.py setup() function like extras_require= as described here: http://docs.readthedocs.io/en/latest/yaml-config.html?highlight=requirements.txt#requirements-file
(and maybe many more. forgive me for not being able to help more on that point)

Don't blame me I don't know how to write python code; I'm just trying to package pyslurm for OSCAR-Cluster  for which I'm now main developper (also main developper of SystemImager as well). and I need at least the man page and html doc.

In the past I contributed a rpm spec file for pyslurm but it never ended here AFAIK.
Now python-setuptools can do bdist_rpm, so it should be useless. The problem is that the generated rpm created using "python setup.py bdist_rpm" is unusable as many file are missing like the doc, the man.1, and the examples.

See https://github.com/oscar-cluster/pkgsrc/tree/master/opkg/jobmonarch/trunk/rpm for a view of my actual specfile that includes docs, examples, manual and has a correct description. the setup.py should be able to produce something similar to my spec file provided extra config is done (I'm unable to help unfortunately)

Note also that pyslurm-17.11.0.7/doc/source/conf.py:36 sphinx.ext.githubpages is an extension that is unavailable in CentOS-7 and CentOS-6 python-sphinx package at least. No way to make that optional?

**Comment by giovtorres** [comment]
Hi @olahaye74 .  There's a lot going on here.  Let's break it down in chunks.  Most of what you are asking is addressable.  I started with adding the missing files to the tarball and updating the version in the docs.

I need to look at the `bdist_rpm` build for generating the rpm.  It works as is on Python 2.7, but not 2.6 (I didn't try Python 3).  However, it depends on `libslurm` and `libslurmdb`, both of which are not packaged, so this might be hard to do since slurm is compiled.

**Comment by olahaye74** [comment]
Hi @giovtorres . excellent!
Though, It seems that recursive-include is ignored by sdist and bdist_rpm. (tested on CentOS-7 python-2.7.5 and Fedora-27 python-2.7.14) (from git clone -b rpm https://github.com/PySlurm/pyslurm.git)

To add to your "chunk list": pyton setup.py sdist should include pyslurm.spec in tarball so the rpm can be built using rpmbuild -tb pyslurm-17.11.0.7.tar.gz

**Comment by olahaye74** [comment]
Here is a setup.cfg that solves a few issues:
[setup.cfg.txt](https://github.com/PySlurm/pyslurm/files/1937519/setup.cfg.txt)
Note that python-nose dependancy is only for tests it it may be removed as the bdist_rpm seems unable to generate a %check section.
python-sphinx build require is for the doc generation. needs some setup.py tweaking IMHO

**Comment by olahaye74** [comment]
To add to your "chunk list": pyton setup.py sdist should include pyslurm.spec in tarball so the rpm can be built using rpmbuild -tb pyslurm-17.11.0.7.tar.gz
I've not yet seen if it's possible to trigger a bdist_rpm --spec-only when doing sdist

**Comment by olahaye74** [comment]
1st step dto doc generation (attachment)
[setup.py.build_doc.patch.txt](https://github.com/PySlurm/pyslurm/files/1938669/setup.py.build_doc.patch.txt)

this is inspired from https://stackoverflow.com/questions/28720624/install-sphinx-compilated-doc-from-setup-py
As stated in the end it might be a good idea to add a Custom command for doc creation.
Unfortunately I've never written python code, so I can't help much.

**Comment by olahaye74** [comment]
python setup.py sdist: Works fine

**Comment by olahaye74** [comment]
enhancement to setup.cfg:
- release more compliant with rpm distros: 1 => 1%{?dist}
- Cython >= 0.15 instead of 0.19 to match setup.py
- python-nose commented out as %check section of rpm is not generated, thus tests aren't run, thus python-nose is not required to build rpm.
- Added /test directory to doc so user can have those tests available when rpm is installed
[setup.cfg.enhancements.patch.txt](https://github.com/PySlurm/pyslurm/files/1941509/setup.cfg.enhancements.patch.txt)

**Comment by olahaye74** [comment]
In distros, python packages are named "python-<pkg_name>" (either deb based distros or rpm based distro do that). For pyslurm, th17.11.0.7e package would be python-pyslurm-17.11.0.7-1.fc27.rpm for fedora or python-pyslurm_17.11.0.7_1.deb if I'm correct
To do so, you can set name="python-pyslurm" in the setup() call. The problem is that it also affects the sdist generated tarball that end as python-pyslurm-17.11.0.7.tar.bz2
So it's up to you to decide if it's wise to do so or not.

**Comment by olahaye74** [comment]
Please can you update setup.cfg with my above patch?
Aside that, abox fix (branch rpm) seems to work fine.

**Comment by giovtorres** [comment]
I merged the requested changes.
