### ISSUE TITLE
Can't build man / html / ... any other doc

### ISSUE THREAD

**Issue by olahaye74** [PySlurm/pyslurm#106]
#### Details

* Slurm Version: 17.11.5
* Python Version: 2.7.14
* Cython Version: 0.27.3
* PySlurm Branch: rpm
* Linux Distribution: fedora-17

#### Issue
Can't build man / html / ... any other doc

0/ python2-sphinx-1.6.6-1.fc27.noarch is installed
1/ git clone -b rpm https://github.com/PySlurm/pyslurm.git
2/ cd pyslurm/doc
3/ make man # or make html

[localhost doc]$ make man
sphinx-build -b man -d build/doctrees   source build/man
Running Sphinx v1.6.6
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index                                                                                                                               
/tmp/pyslurm/doc/source/index.rst:25: WARNING: autodoc: failed to import class u'block' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:31: WARNING: autodoc: failed to import class u'config' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:37: WARNING: autodoc: failed to import class u'front_end' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:43: WARNING: autodoc: failed to import class u'hostlist' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:49: WARNING: autodoc: failed to import class u'job' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:55: WARNING: autodoc: failed to import class u'jobstep' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:61: WARNING: autodoc: failed to import class u'node' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:67: WARNING: autodoc: failed to import class u'partition' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:73: WARNING: autodoc: failed to import class u'reservation' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:79: WARNING: autodoc: failed to import class u'slurmdb_events' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object                                                                   
    __import__(self.modname)                                                                                                                                  
ImportError: No module named pyslurm                                                                                                                          
/tmp/pyslurm/doc/source/index.rst:85: WARNING: autodoc: failed to import class u'slurmdb_reservations' from module u'pyslurm'; the following exception was raised:                                                                                                                                                          
Traceback (most recent call last):                                                                                                                            
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named pyslurm
/tmp/pyslurm/doc/source/index.rst:91: WARNING: autodoc: failed to import class u'slurmdb_clusters' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named pyslurm
/tmp/pyslurm/doc/source/index.rst:97: WARNING: autodoc: failed to import class u'slurmdb_jobs' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named pyslurm
/tmp/pyslurm/doc/source/index.rst:103: WARNING: autodoc: failed to import class u'statistics' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named pyslurm
/tmp/pyslurm/doc/source/index.rst:109: WARNING: autodoc: failed to import class u'topology' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named pyslurm
/tmp/pyslurm/doc/source/index.rst:115: WARNING: autodoc: failed to import class u'trigger' from module u'pyslurm'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named pyslurm
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... pyslurm.1 { } 
build succeeded, 16 warnings.

Build finished. The manual pages are in build/man.

**Comment by giovtorres** [comment]
@olahaye74 You first need to build and install the pyslurm module globally, then you can use sphinx to build the docs.

**Comment by olahaye74** [comment]
@giovtorres  Can't we provide the library path to sphynx from build-dir?
Can't we have an LD_LIBRARY_PATH set to locally built pyslurm.so?

Or better, remove the doc/Makefile and build the doc from setup.py .
if __name__ == "__main__":
    setup_package()
    # generate documentation
    import sphinx
    import sys
    sys.path.insert(0, "build/lib.linux-x86_64-2.7/pyslurm") # UGLY, need cleaner way to do things
    sphinx.cmd.build.make_main(['setup.py', '-b', 'html', '-d', 'doc/build/doctrees', 'doc/source', 'doc/build/html'])
    sphinx.cmd.build.make_main((['setup.py', '-b', 'man', '-d', 'doc/build/doctrees', 'doc/source', 'doc/build/man'])

**Comment by giovtorres** [comment]
I couldn't get this to work on my first attempt. I'll give it another try later.

Ideally, I'd like the docs to build and pushed to pyslurm.github.io whenever there is a merge to master.  That happens now, but it doesn't feel very elegant.

**Comment by giovtorres** [comment]
Yes, I do agree.  I think in OpenBSD, they consider the lack of a manpage a bug.

I'll look at the man page generation.

**Comment by giovtorres** [comment]
Fixed in PR #112

**Comment by giovtorres** [comment]
Hi @olahaye74 , can you confirm man pages are building for you?  It is building locally.  Actually, I hadn't built the man pages before using Sphinx.  This is nice to have.

**Comment by olahaye74** [comment]
git clone https://github.com/PySlurm/pyslurm.git
cd pyslurm/
python setup.py build
# man is nout build, doc is not built
cd doc
make man
phinx-build -b man -d build/doctrees   source build/man
Making output directory...
Running Sphinx v1.1.3

Exception occurred:
  File "/tmp/pyslurm/doc/source/conf.py", line 18, in <module>
    from pyslurm import __version__
ImportError: No module named pyslurm
The full traceback has been saved in /tmp/sphinx-err-vux2Hy.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [man] Error 1

a dirty hack on setup.py (on fedora 27 which ships with sphinx-1.6.6) can produce the doc:
# generate documentation
import sphinx
import sys
sys.path.insert(0, "build/lib.linux-x86_64-2.7/pyslurm") # UGLY, need cleaner way to do things
sphinx.build.make_main(['setup.py', '-b', 'html', '-d', 'doc/build/doctrees', 'doc/source', 'doc/build/html'])
sphinx.build.make_main(['setup.py', '-b', 'man', '-d', 'doc/build/doctrees', 'doc/source', 'doc/build/man'])

but I'm unable to reproduce that on CentOS-7 which ships with sphinx-1.1.4, and as I'm not a python programmer at all, I'm unable to determine if it's a lack of support or and other method that I should use. Also, this code must be put elsewhere I think.

Maybe a solution here: https://github.com/vcstools/wstool/blob/master/setup.py#L63
I can't help more except by testing.

**Comment by olahaye74** [comment]
Big progress :-)
enhanced setup.cfg that includes [sphinx_build] section
doc/source/conf.py that knows the correct path to build module so it can import pyslurm eventhough it is not yet installed on system. (I think you can do better as I'm not python developper and specifying the hardcoded linux build dir is ugly. I convinced there is a variable for that. I was unable to use the module from the source directory (if I put ../.. so it can find pyslurm/__init__.py, it cant find the module).
[setup.cfg.txt](https://github.com/PySlurm/pyslurm/files/2032050/setup.cfg.txt)
[doc_source_conf_py.patch.txt](https://github.com/PySlurm/pyslurm/files/2032051/doc_source_conf_py.patch.txt)
setup.py is thus left untouched.
Then to build everything I do:
python setup.py build
python setup.py build_sphinx -bman
python setup.py build_sphinx -bhtml
I don't know how to tell setup.py to build the sphinx doc when doing the build
I also don't know how to specify more than one builder in [build_sphinx] section of setup.cfg
(tested on CentOS-7 with python-sphinx-1.1.3-11.el7.noarch)

**Comment by giovtorres** [comment]
Hi @olahaye74, I've been a bit absent, but would like to pick this up again.

Where would the `slurm-devel`, `slurm-slurmd` and `slurm-slurmdbd` packages come from?  Wouldn't this fail if the user doesn't have these packages available in a configured repository?

Are there any official Slurm RPM repos out there that users can leverage?

**Comment by olahaye74** [comment]
I maintain the OSCAR Cluster repository here: http://svn.oscar.openclustergroup.org/repos/unstable/
but this hosting is subject to change in the future.
The rpm packages are built suing the simple command: rpmbuild -tb slurm-17.11.6.tar.bz2

**Comment by giovtorres** [comment]
I added the suggested changes.
