### ISSUE TITLE
update debian/ packaging infos.

### ISSUE THREAD

**Issue by olahaye74** [PySlurm/pyslurm#107]
#### Details

    Slurm Version: slurm-devel-17.11.5-1.el7
    Python Version: python-2.5.7-58.el7
    Cython Version: Cython-0.19-5.el7
    PySlurm Branch: master
    Linux Distribution: CentOS-7 (also on Fedora-27 and maybe CentOS-6)

#### Issue
update debian packaging that is outdated.
A maintained debian dir can be found here:
https://github.com/edf-hpc/python-pyslurm/tree/master/debian
The control file needs update regarding  required versions like Cython.

I don't understand the lib patch detection, and I think it is wrong.
BUT, the changelog and gbp.conf are correct IMHO
there are also many changes in the setup.py, so bee carefull with this fork when trying to backport stuffs.
Or maybe you can poropose the author to work on a "debian" branch on your tree?

**Comment by giovtorres** [comment]
Yes, the debian directory is quite old and certainly needs some attention.  In terms of packaging, I'm familiar with RPM but not Deb.  Do you want to give it a try?

**Comment by olahaye74** [comment]
I' hate debian packaging eventhough I had to do some for OSCAR Cluster. This system based on old make utility whith fake macros is really horrible to create and maintain.
spec files look so modern compared to debian system :)
If I have time I'll try to do something and submit a patch here. (I have to work on OSCAR debian backaging, so, as pyslurm is part of OSCAR distro, I will certainly work on it.)
Don't expect this soon though :)

**Comment by giovtorres** [comment]
ok, no problem.  I'll close this for now.  Do submit a PR if you get a chance soon to submit updates to the `debian/` directory.  Thanks!
