### ISSUE TITLE
Avoid defining  version in multiple places

### ISSUE THREAD

**Issue by olahaye74** [PySlurm/pyslurm#108]
Avoid defining  version in multiple places (setup.py, pyslurm/__init__.py, doc/source/conf.py, ...)

A good explanation here with example
https://stackoverflow.com/questions/26141851/let-sphinx-use-version-from-setup-py
Multiple techniques explained
https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by olahaye74** [comment]
I do my best to help, but as I'm not python programmer, I can't help more unfortunately :-)

**Comment by giovtorres** [comment]
You can always use a project like this as an opportunity to learn Python/Cython.  The codebase is not large and most of the classes follow the same structure.  I knew zero Cython before and used this project to learn it.  Travis CI offers some comfort and is there to help us contributors catch mistakes and errors before merging to master.

**Comment by olahaye74** [comment]
sure! but I'm already main developper for SystemImager (alone), OSCAR Cluster (alone) and a few other stufs where I contributed packaging or patches like jobmonarch, ganglia, ... and I must admit I have no time left :-/

**Comment by giovtorres** [comment]
Closing this for now.  I'll handle building/versioning the docs on GitHub separately.
