### ISSUE TITLE
slurmdb_jobs() kills the python process

### ISSUE THREAD

**Issue by jaysharm** [PySlurm/pyslurm#110]
#### Details

* Slurm Version: 17.11.3
* Python Version: 3.6.2
* PySlurm Branch: 17.11.0
* Linux Distribution: Red Hat 4.4.7-1

#### Issue

Hi,

Given that jobs drop out of the cache after 300 seconds, I was trying to replicate the functionality of ``sacct -j <jobid>``.  But slurm_db_jobs() kills the python process with the below error?

```python
>>> from pyslurm import slurmdb_jobs
>>> slurmdb_jobs().get([47764])
python3.6: fatal: list.c:257 list_count: pthread_mutex_lock(): Invalid argument

Process finished with exit code 1
```

**Comment by giovtorres** [comment]
Hi @jaysharm, I'm able to replicate on python 2 and 3.  I'll have a look.

**Comment by viennej** [comment]
Hi,

I am seeing the same thing with Pyslurm 18.0.0 with Slurm 18.08.3.
Do you have an update regarding this issue?

Thanks

**Comment by giovtorres** [comment]
No.  I tried to track it down, but the slurmdb api is not documented at all, making it difficult to wrap properly.  I managed to get a core dump file.  I had to use a VM and not a container.  The problem lies here: https://github.com/PySlurm/pyslurm/blob/18-08-3/pyslurm/pyslurm.pyx#L5314.  I'll keep looking.

**Comment by giovtorres** [comment]
@jaysharm apologies for the very long delay.  I think I'm finally starting to understand the slurmdb code.  I pushed 4a7eeda, 429749f, 18a7c65 to `master`, which should fix this.

**Comment by giovtorres** [comment]
This should be fixed now. Please re-open if you are still having issues.
