### ISSUE TITLE
doc/source/conf.py inconsitent requirements.

### ISSUE THREAD

**Issue by olahaye74** [PySlurm/pyslurm#113]
needs_sphinx = '1.1'
is inconsistent with:
extensions = [
...
    'sphinx.ext.githubpages'
]

sphinx.ext.githubpages is only available in sphinx V1.4+.
=> Either remove this extension, OR, set need_sphinx = '1.4'

Note: CentOS-7 ships with sphinx V1.1.3 (which is far from V1.4)

**Comment by giovtorres** [comment]
Thanks.  See f5c7fc1 in #114
