### ISSUE TITLE
/doc/source/conf.py: html_theme = 'classic' does not exists on sphinx V1.1

### ISSUE THREAD

**Issue by olahaye74** [PySlurm/pyslurm#114]
html_theme = 'classic' does not exists in sphinx V1.1.3 (CentOS-7 and previous)

Using
html_theme = 'default'
Works fine.
(Tested on CentOS-7)

Note: classic theme appeared in sphinx V1.3
https://github.com/sphinx-doc/sphinx/commit/68021b0bd3174a488b965e7425a39a1add806a75

Available themes for sphinx V1.1.3 (CentOS-7) are listed here: https://github.com/sphinx-doc/sphinx/tree/v1.1.3/sphinx/themes

**Comment by giovtorres** [comment]
I made the suggested changes. Thanks @olahaye74
