### ISSUE TITLE
username as key in the output of pyslurm.job().get()

### ISSUE THREAD

**Issue by wfarah** [PySlurm/pyslurm#125]
#### Details

* Slurm Version: 17.11.7
* Python Version: 2.7.15
* Cython Version: 0.28.3
* PySlurm Branch: 17.11.0.9
* Linux Distribution: CentOS Linux release 7.5.1804 (Core)

#### Issue

Hi,

The job description dictionary contains only 'user_id' as key. There can be multiple users for a given account, so I can't use 'account' key in the particular application that I'm writing. It would be really useful if the job description dictionary can have a 'user_name' key.

Thanks!
Wael

**Comment by giovtorres** [comment]
I believe I tried this in the past and passing the user_id through the C passwd functions for a site with a large number of users (100s) significantly reduced the performance of the get() method (See a small write up here: https://github.com/PySlurm/pyslurm/wiki/Profiling-PySlurm#using-line_profiler).  I think Slurm might be caching the passwd file for better performance.

You could use python's  pwd.getpwnam and pwd.getpwuid functions to translate a user's username into a userid before passing it onto pyslurm.  Wouldn't that work for you?

**Comment by wfarah** [comment]
No worries! I think I got myself going with functions from the pwd module. It should be fine from there. I'll close the issue, thanks for your help.
