### ISSUE TITLE
Support for slurm 18.08

### ISSUE THREAD

**Issue by markuskowa** [PySlurm/pyslurm#126]
#### Details
* Slurm Version: 18.08.0-1
* PySlurm Branch: master
* Linux Distribution: NixOS

#### Issue
Slurm 18.08 was released 5 days ago.  I was trying to update Slurm in NixOS and recognized that PySlurm does not support Slurm 18.08 yet.

**Comment by giovtorres** [comment]
Update to Slurm 18.08.0 is complete.  Please see the 18.08.0 branch, not master.
