### ISSUE TITLE
There really needs to be a way to use env vars for setting params like SBATCH_xxx

### ISSUE THREAD

**Issue by akesandgren** [PySlurm/pyslurm#130]
Just like slurms src/sbatch/opt.c handles env vars before it is calling the API, there should be the same type of handling in pyslurm.
Either using the SBATCH_xxx env vars or pyslurm specific ones.

**Comment by tazend** [comment]
This is now supported via the [new Job submission API](https://pyslurm.github.io/23.2/reference/jobsubmitdescription/#pyslurm.JobSubmitDescription) (at the moment just for slurm 23.02, but it will be backported to a few earlier versions soon)

pyslurm however does not use the `SBATCH_` prefix, but its own specific one, `PYSLURM_JOBDESC_`. Everything after the prefix must match an existing attribute in `JobSubmitDescription`. Loading the environment variables must be explicitly triggered, and is not done by default.

For an example, please check [here](https://pyslurm.github.io/23.2/reference/jobsubmitdescription/#pyslurm.core.job.submission.JobSubmitDescription.load_environment)
