### ISSUE TITLE
pyslurm reporting different memory values since update to 18.08.x

### ISSUE THREAD

**Issue by wccropper** [PySlurm/pyslurm#131]
#### Details
* Slurm Version:18.08.3
* Python Version: 3.6.6
* Cython Version: 0.28.5
* PySlurm Branch: 18.08.3 tag
* Linux Distribution: CentOS 7.5

#### Issue
Pyslurm is reporting the memory requested differently than what it did before. For example; we request 50G of memory for a worker job, which is stored in a string.  When the pipeline looks for worker jobs with the amount of memory allocated, pyslurm says that the jobs have 50000M of memory.  50G != 50000M on a string level.

**Comment by giovtorres** [comment]
Could you share the output of the commands you are running?

**Comment by giovtorres** [comment]
@wccropper Could you please share the slurm output and pyslurm output for the memory discrepancy you are having so I can replicate it?
