### ISSUE TITLE
Wrong partition information is returned by get_node()

### ISSUE THREAD

**Issue by martijnkruiten** [PySlurm/pyslurm#133]
#### Details

* Slurm Version: 18.08.3
* Python Version: 2.7.13
* Cython Version: 0.25.2
* PySlurm Branch: 18.08.0
* Linux Distribution: Debian 9

#### Issue
`get_node()` returns wrong partition information, while `get()` does not.

```
In [10]: import pyslurm

In [11]: s = pyslurm.node()

In [12]: s.get_node('software2')
Out[12]: 
{u'software2': {u'alloc_cpus': 0,
  ...
  u'partitions': [u'gpu_sw'],
  ...

In [13]: s.get()
Out[13]: 
 u'software2': {u'alloc_cpus': 0,
  ...
  u'partitions': [u'sw'],
  ...
```

With `get_node()`, all nodes return 'gpu_sw' as their partition, while that partition only contains one node. With `get()` the correct partition is returned.

**Comment by giovtorres** [comment]
Hi @martijnkruiten.  I am able to replicate, although I get a different wrong answer.  I'll take a deeper look, as I may need to update the wrapping.

**Comment by giovtorres** [comment]
@martijnkruiten Could you try this fix when you get a chance?  Thanks.

**Comment by martijnkruiten** [comment]
Hi @giovtorres, the fix works for me. I get an empty list for nodes without a partition and a complete and correct list for nodes with one or more partitions. Thanks!
