### ISSUE TITLE
access qos failed with undefined symbol error

### ISSUE THREAD

**Issue by fengpinghu** [PySlurm/pyslurm#136]
#### Details

* Slurm Version:
18.08.4
* Python Version:
2.7.12
* Cython Version:
0.23.4-0ubuntu5
* PySlurm Branch:
18.08.0
* Linux Distribution:
Ubuntu 16.04.3 LTS
#### Issue

access qos failed with undefined symbol error

Type "help", "copyright", "credits" or "license" for more information.
>>> import pyslurm
>>> job=pyslurm.job()
>>> job.get()
{}
>>> job.ids()
[]
>>> qos=pyslurm.qos()
>>> qos.get()
python: symbol lookup error: /usr/lib64/slurm/accounting_storage_slurmdbd.so: undefined symbol: slurmdbd_pack_fini_msg

$ nm /usr/lib64/libslurm.so | grep slurmdbd_pack_fini_msg
0000000000134f9d t slurmdbd_pack_fini_msg

**Comment by giovtorres** [comment]
@fengpinghu Could you please re-test with the latest change to the 18.08.0 branch?

**Comment by martijnkruiten** [comment]
This works for me on Debian 9.6 with Slurm 18.08.5, so I think it can be closed.

**Comment by giovtorres** [comment]
@martijnkruiten Thanks for verifying.  I also added 0146103 as basic check to catch this in the future.
