### ISSUE TITLE
pyslurm google group is not open

### ISSUE THREAD

**Issue by JimCircadian** [PySlurm/pyslurm#139]
#### Details

N/A

#### Issue

The link provided in README for the pyslurm google group is not accessible to the public: https://groups.google.com/forum/#!forum/pyslurm

**Comment by giovtorres** [comment]
Hi, the group is world readable, but in order to post, you just need to request access to the Google group.

**Comment by giovtorres** [comment]
Hi, the group is world readable, but in order to post, you just need to request access to the Google group.

**Comment by JimCircadian** [comment]
This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the owner of the group and ask them to give you access.

**Comment by giovtorres** [comment]
Looks like Google updated their default Google Groups permissions.  I updated it accordingly and it should be visible now.  Please let me know if that is not the case.

**Comment by JimCircadian** [comment]
All good now, thanks!
