### ISSUE TITLE
SLURM 19 compatibility

### ISSUE THREAD

**Issue by whowell** [PySlurm/pyslurm#142]
#### Details

* Slurm Version: 19.05
* Python Version: 2.7, 3.6
* Cython Version: 0.28.5
* PySlurm Branch: 
* Linux Distribution: RHEL 7

#### Issue
Are there any plans or a timeline for SLURM version 19+ compatibility?

**Comment by giovtorres** [comment]
Plans, yes.  Started working on it yesterday.

**Comment by whowell** [comment]
Thank you @giovtorres for the update and quick response. I'll close this as it was just a general question.
