### ISSUE TITLE
"jobs_running" and "jobs_pending" fields missing?

### ISSUE THREAD

**Issue by hawson** [PySlurm/pyslurm#143]
#### Details

* Slurm Version:  19.05.2
* Python Version: 3.6.8
* Cython Version: 0.29.12
* PySlurm Branch: 19.5.0.0
* Linux Distribution: CentOS 7.6.1810

#### Issue

The fields `jobs_running` and `jobs_pending` are not exported.

A simple example on a small cluster with one job running:
```
$ sdiag | egrep 'Jobs (pending|running)'
Jobs pending:   0
Jobs running:   1
```

However, these fields are not exported via pyslurm:
```
$ python examples/stats.py |egrep 'jobs_'
jobs_submitted            : 2                
jobs_started              : 2                
jobs_completed            : 2                
jobs_canceled             : 0                
jobs_failed               : 0                
```

I believe that at least jobs_running worked in the 17.x branch several months back, but I can't tell if this is a PySlurm problem, or if this build of Slurm isn't exporting the values.  I'm not aware of any other missing metrics (but I have not done an exhaustive search either).

**Comment by giovtorres** [comment]
Can you give it a try now?

**Comment by hawson** [comment]
Finally got a chance to test this.  The fix appears to work.

**Comment by nierodal** [comment]
They are missing in 18-08-8 as well

**Comment by giovtorres** [comment]
@nierodal Added here af3a583

**Comment by nierodal** [comment]
Thanks!
