### ISSUE TITLE
rpmbuild failed. xmalloc not found.

### ISSUE THREAD

**Issue by abrekhov** [PySlurm/pyslurm#147]
#### Details

* Slurm Version: 19.05.3
* Python Version: 2.7.5
* Cython Version: 0.19
* PySlurm Branch: 19.05.0 release
* Linux Distribution: centos 7.6.1810

#### Issue
I'm trying to make an rpmbuild.
Im going to directory of project. 
Then
`python setup.py bdist_rpm`
After that error:
`creating build/temp.linux-x86_64-2.7/pyslurm
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I/usr/include -I. -I/usr/include/python2.7 -c pyslurm/pyslurm.c -o build/temp.linux-x86_64-2.7/pyslurm/pyslurm.o
pyslurm/pyslurm.c:314:21: fatal error: xmalloc.h: No such file or directory
 #include "xmalloc.h"`

But build and install of pyslurm is working.

**Comment by giovtorres** [comment]
`pyslurm/xmalloc.h` needs to get added to `MANIFEST.in`. Would you mind doing a PR?
