### ISSUE TITLE
Retrieve completed jobs through the jobs class

### ISSUE THREAD

**Issue by vrindger** [PySlurm/pyslurm#164]
#### Details

* Slurm Version: 18.08.8
* Python Version: 2.7.15
* Cython Version: 0.25+ i think
* PySlurm Branch: 18.08.8
* Linux Distribution: centos

#### Issue
@giovtorres Is there a way to retrieve historical job information from the pyslurm.job class or from pyslurm in general ? The behavior I'm noticing is that as my job array completes or even continues to churn through the array, the jobs stop showing up in jobs.get() and I can't look them up using jobs.find or jobs.find_id anymore.

This is important for us to be able to track our array if it completed or not. Please let me know if this is possible. It doesnt have to be realtime, I just need to be able to look up jobs by ids even after they're done. 

Thanks so much for this wonderful package that has helped us a lot!

**Comment by vrindger** [comment]
So right now no jobs are running and this is what I see:
>>> import pyslurm
>>> jobs = pyslurm.job()et()
{}

**Comment by vrindger** [comment]
I tried using slurmdb_job() just now. I'm seeing erratic behavior with it. It seems that I have to exit python, create a new python instance and then get the jobs for it to show the latest jobs. Does this sound familiar? I'm now dropping pyslurm for job tracking and thinking of running sacct in a subprocess command now. If you have a reliable way to get the same information as sacct, please let me know. I would love to be able to use pyslurm instead for this

**Comment by giovtorres** [comment]
I believe the sacct database will have this information. Unfortunately, the slurmdb api is a bit tricky to wrap with Cython. It is not documented and my attempt to ask for examples or documentation was rejected years ago. I was told the code is self documenting. I disagree.

The slurmdb portion of the code definitely needs some work. I'd love some contributions around this part of the API :pray:

**Comment by vrindger** [comment]
Yes using the sacct command works so I might switch to using the mariadb before going back to pyslurm. That's a good suggestion thanks. I did not get consistent results with slurmdb_job or job. The lack of documentation is very challenging for sure. I might revisit it some day but I don't have much bandwidth for looking into this. Just needed a way to track job array completion in realtime and print a summary once done

**Comment by giovtorres** [comment]
Now that 20.02-pre is out, I will try to finally push out v2 of the PySlurm API, which should hopefully have better support for the DB API and job submission :pray:

**Comment by vrindger** [comment]
Nice. I see. I'll try to upgrade our slurm here too after that.. From 18 to 20 I guess
