### ISSUE TITLE
--format option?

### ISSUE THREAD

**Issue by vladdoster** [PySlurm/pyslurm#165]
#### Details

* Slurm Version: Latest
* Python Version: 3.4
* Cython Version: Latest
* PySlurm Branch: Master
* Linux Distribution: Arch

#### Issue
Not an issue, but a question. Is there anyway to pass the --format flag to retrieve certain fields instead of retrieving all fields which would save me having to add extra logic to filter them later.

If not, do we think this is able to be implemented? I'd be down to do it because I would use the hell out of it because it would reduce amount of logic I need in our API.

**Comment by vladdoster** [comment]
In slurmdb_jobs.get() I see something about flags. Is something I can send the format flag too?

https://github.com/PySlurm/pyslurm/blob/master/pyslurm/pyslurm.pyx#L5381

**Comment by giovtorres** [comment]
There is not. Instead of passing multiple formatting fields, we should probably set this to `ALL` and just return everything upfront to the user to pick and choose from.

We'd have to figure out the field parsing logic here: https://github.com/SchedMD/slurm/blob/slurm-19-05-5-1/src/sacct/options.c#L1465

Would this approach match your use case?

**Comment by vladdoster** [comment]
Yes, that would work. So is there somewhere in Pyslurm you all don't set it to ALL? I don't quite understand what moving parts would need to be touched. Ideally in the slurmdb_jobs API method where starttime & endtime are passed I would be able to pass an kwarg named format an array of fields I would like back. 

So you're saying we would retrieve all fields and then add the filtering logic to pyslurm?

**Comment by vladdoster** [comment]
I apologize about me not understanding, I've only been introduced to Slurm for < 2 weeks.

**Comment by vladdoster** [comment]
But am more than happy to knock it out if I get a better understanding of what needs to be done. I am capable!

**Comment by giovtorres** [comment]
I'd be happy to get some contributions!

**Comment by vladdoster** [comment]
I am still not too sure where changes would need to be made in PySlurm?

**Comment by vladdoster** [comment]
Hi @giovtorres,

I am currently trying to mimic sacct. In the default `sacct` option it displays `alloc_cpu` in the table. In the slurmdb_jobs class it doesnt seem to give me that back in the dict I receive.  Does it pull it or is there somewhere I can pull that from so I can add it to my table?
