### ISSUE TITLE
Retrieve batch jobs?

### ISSUE THREAD

**Issue by vladdoster** [PySlurm/pyslurm#166]
#### Details

* Slurm Version: 19.05
* Python Version: 3.4
* Cython Version: 
* PySlurm Branch: Master
* Linux Distribution: Arch

#### Issue
When retrieving jobs using sacct, it returns the following:
![pic-selected-200213-0905-37](https://user-images.githubusercontent.com/10052309/74443166-bdf45000-4e40-11ea-8c41-4451d76af850.png)

but using pyslurm I just get the jobs and not the batch. Anyway to retrieve the batch using PySlurm?

**Comment by giovtorres** [comment]
I believe the whole integration with the slurm DB API needs to be enhanced to provide the details you are looking for. :disappointed:

**Comment by vladdoster** [comment]
@giovtorres We have moved to wrapping `sacct` with subprocess module :)

**Comment by vkantchev** [comment]
batch step is returned as a step by pyslurm.slurmdb_jobs().get

See def test_slurmdb_jobs_get_steps(): in:
https://github.com/PySlurm/pyslurm/blob/master/tests/test_slurmdb.py
