### ISSUE TITLE
Jobs of hidden partitions not available

### ISSUE THREAD

**Issue by hillenbrkl** [PySlurm/pyslurm#170]
#### Details

* Slurm Version: 19.05.5
* Python Version: 3.6
* Cython Version: 0.19
* PySlurm Branch: 19.05.0
* Linux Distribution: EL7

#### Issue

pyslurm.job().get() does not contain jobs that are submitted to or running in a hidden partition (like scontrol show jobs -a would).

pyslurm.partition().get() on the other side contains all partitions, including the hidden.

It would be reasonable to also get the hidden jobs with pyslurm.job() and leave the filtering to the user.

**Comment by giovtorres** [comment]
I agree. It would be reasonable. I'd love a contribution for this enhancement :wink:

**Comment by schluenz** [comment]
in pyslurm.pyx
`self._ShowFlags = slurm.SHOW_DETAIL | slurm.SHOW_DETAIL`

looks like a typo. _Naively_ replacing it by 
`self._ShowFlags = slurm.SHOW_DETAIL | slurm.SHOW_ALL`

seems to give me a complete job-list.
