### ISSUE TITLE
How to set env-var for job

### ISSUE THREAD

**Issue by saidst** [PySlurm/pyslurm#173]
#### Details

* Slurm Version: 19.05
* Python Version: 3.6.8
* Cython Version: 0.29.16
* PySlurm Branch: master
* Linux Distribution: centos 7

#### Issue

I try to pass a custom env-var to a batch-job like that. It is not populated to the environment of the wrapped commands.

```
test_job = {
  "job_name": "env-echo",
  "user_id": "0",
  "wrap": "srun /usr/bin/echo ${MY_SPECIAL_ENV_VAR}; srun /usr/bin/env | grep MY_SPECIAL_ENV_VAR;",
  "export": "MY_SPECIAL_ENV_VAR=abcdef"
}
```
**What is the syntax to use for the export-key?**

**Comment by giovtorres** [comment]
Could you try exporting the variable and then submit a test job with `"export_env": "ALL"` instead of `export`?

**Comment by saidst** [comment]
Thanks for the answer. we stopped using pyslurm for the time-beeing. As we start again, I will check that out.
