### ISSUE TITLE
How to add nodes to cluster?

### ISSUE THREAD

**Issue by XueCangQiuYe** [PySlurm/pyslurm#174]
Hi, I have a question about how to add nodes.

If I have a node to join the cluster, as far as I know, I need to modify `slurm.conf` and use `scontrol reconfigure` to enable configure.

Do puslurm have some tools to add nodes to cluster easily ?

**Comment by giovtorres** [comment]
No. I don't believe the Slurm API offers this capability. I think you can add a node to a partition and then reconfigure, both with PySlurm, but I'm not sure that updating a partition will write the change to slurm.conf. You could give it a try and let us know.
