### ISSUE TITLE
Incorrect req_mem value return by slurmdb_jobs

### ISSUE THREAD

**Issue by 0luhancheng0** [PySlurm/pyslurm#183]
#### Details

* Slurm Version:20.02.6
* Python Version:3.8.7
* Cython Version:0.29.23
* PySlurm Branch:42a1f20 (latest commit) on master branch
* Linux Distribution:Centos7

### Issue
req_mem field returned by in slurmdb_jobs() does not reflect the actual value. 

```
>>> pyslurm.slurmdb_jobs().get(jobids=[7140959])[7140959]['req_mem']
9223372036854779904
```

```
[luhanc@monarch-login2 ~]$ sacct --format JobID,ReqMem
       JobID     ReqMem
------------ ----------
7140958             4Gc
7140959             4Gc
```

**Comment by tazend** [comment]
Yeah I can confirm, I'm also getting this value returned. I had a look at how they do it in **sacct** and there is this code:

```
if (tmp_uint64 & MEM_PER_CPU)  {
    tmp_uint64 &= (~MEM_PER_CPU);
    per_cpu = true;				
}
```
This does the magic, after quickly putting it in and testing it I'll then get the value "4096" when --mem-per-cpu=4G is used.
I see if I can make a pull-request for this.

**Comment by 0luhancheng0** [comment]
Hi @tazend, is there any update regarding the issue? And it would be great if you can make a pull request. Thanks

**Comment by tazend** [comment]
hi @0luhancheng0 , haven't had much time recently, but I should get it done this week.
