### ISSUE TITLE
python3-pyslurm dependency of slurm-web-restapi

### ISSUE THREAD

**Issue by liu-shaobo** [PySlurm/pyslurm#235]
hi，all，How to solve this problem
#### Details
* Slurm Version: 19.05.7
* Python Version: python3.6
* Cython Version:  python36-Cython-0.28.6
* PySlurm Branch:  19.05.0
* Linux Distribution: Centos-7.6

#### Issue
[root@node001 pyslurm]# python3.6 setup.py install
/usr/lib/python3.6/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '19.05.0.0' to '19.5.0.0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing pyslurm.egg-info/PKG-INFO
writing dependency_links to pyslurm.egg-info/dependency_links.txt
writing requirements to pyslurm.egg-info/requires.txt
writing top-level names to pyslurm.egg-info/top_level.txt
reading manifest file 'pyslurm.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyslurm.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
skipping 'pyslurm/pyslurm.c' Cython extension (up-to-date)
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pyslurm
copying build/lib.linux-x86_64-3.6/pyslurm/__init__.py -> build/bdist.linux-x86_64/egg/pyslurm
copying build/lib.linux-x86_64-3.6/pyslurm/__version__.py -> build/bdist.linux-x86_64/egg/pyslurm
copying build/lib.linux-x86_64-3.6/pyslurm/pyslurm.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pyslurm
byte-compiling build/bdist.linux-x86_64/egg/pyslurm/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyslurm/__version__.py to __version__.cpython-36.pyc
creating stub loader for pyslurm/pyslurm.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/pyslurm/pyslurm.py to pyslurm.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pyslurm.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyslurm.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyslurm.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyslurm.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyslurm.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
pyslurm.__pycache__.pyslurm.cpython-36: module references __file__
creating 'dist/pyslurm-19.5.0.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyslurm-19.5.0.0-py3.6-linux-x86_64.egg
creating /usr/local/lib64/python3.6/site-packages/pyslurm-19.5.0.0-py3.6-linux-x86_64.egg
Extracting pyslurm-19.5.0.0-py3.6-linux-x86_64.egg to /usr/local/lib64/python3.6/site-packages
Adding pyslurm 19.5.0.0 to easy-install.pth file

Installed /usr/local/lib64/python3.6/site-packages/pyslurm-19.5.0.0-py3.6-linux-x86_64.egg
Processing dependencies for pyslurm==19.5.0.0
Searching for Cython==0.28.6
Best match: Cython 0.28.6
Adding Cython 0.28.6 to easy-install.pth file
Installing cygdb script to /usr/local/bin
Installing cython script to /usr/local/bin
Installing cythonize script to /usr/local/bin

Using /usr/lib64/python3.6/site-packages
Finished processing dependencies for pyslurm==19.5.0.0

[root@node001 x86_64]# rpm -ihv slurm-web-restapi-2.4.0-1.el7.edf.x86_64.rpm
**error: Failed dependencies:**
	python3-pyslurm is needed by slurm-web-restapi-2.4.0-1.el7.edf.x86_64

**Comment by tazend** [comment]
Hi,

As far as I am aware, the pyslurm project here does not officially provide any RPMs to install pyslurm (maybe in the future?).
Therefore, I am not sure why python3-pyslurm is a dependency, since the RPM doesn't exist anywhere to my knowledge.

I'd recommend raising an issue at the [slurm-web project](https://github.com/edf-hpc/slurm-web/issues), pointing out that `python3-pyslurm` doesn't really exist in any official repository and it might be better to remove it from the spec file. The offending Line in the spec file is [here](https://github.com/edf-hpc/slurm-web/blob/master/rhel/slurm-web.spec#L87)
