### ISSUE TITLE
Status of Slurm 22.05.x compability

### ISSUE THREAD

**Issue by staeglis** [PySlurm/pyslurm#237]
Hi,

has some tested pylsurm with Slurm 22.05.x already?

Best,
Stefan

**Comment by tazend** [comment]
Hi @staeglis 

Not yet, but I can check to see whats necessary for 22.05 and try to add support for it.

**Comment by tazend** [comment]
Working on it now, might have it done by Wednesday, seems that only a few things have to be adjusted.

**Comment by staeglis** [comment]
Hi @tazend,

thank you very much for the fast progress. I will test it soon after the arrival of Slurm 22.05 in Debian Sid.

**Comment by tazend** [comment]
Just made a new release for PySlurm:  22.5.0 (to work with any Slurm 22.05.X Version)
(which also includes some more changes to the build-system -> setup.py)

So I think this can be closed.
