### ISSUE TITLE
missing job field 'comment'

### ISSUE THREAD

**Issue by Whitehorse2** [PySlurm/pyslurm#244]
#### Details

* Slurm Version: 20.11.8-1
* Python Version: 3.8
* Cython Version: 0.29.32 
* PySlurm Branch: slurm-20.11.8
* Linux Distribution: ubuntu 20.04

#### Issue
From the pyslurm [job database output](https://github.com/PySlurm/pyslurm/blob/main/examples/listdb_jobs.py), i am missing the 'comment' and tmp disk section.

Why is the data missing and can it be added?

Thanks in advance

**Comment by tazend** [comment]
Hi @Whitehorse2 

just had a look, yeah fetching the comment from the database output just isn't implemented currently. I can check it out on the weekend.

Can you clarify what you mean with "tmp disk"? Maybe you can tell me the exact name of the property you want to retrieve? (by checking with `sacct -e`)

**Comment by Whitehorse2** [comment]
@tazend : Thank you, could you integrate this value at branch `slurm-20.11.8` ?
I mean the `MIN_TMP_DISK` value, visible at `squeue`, but I could not find it at `sacct`.

**Comment by tazend** [comment]
Hi @Whitehorse2 

I have added a "comment" field in the slurmdb jobs output in the branch you mentioned (https://github.com/PySlurm/pyslurm/commit/b3cc3656318221a8bfdcc8224a8e1b9293411298)

In regards to the `MIN_TMP_DISK` - for Jobs fetched from the database this information isn't available.

But for jobs which are still running/pending, you can use `job().get()` and then the field is called `pn_min_tmp_disk`. (that what squeue reports)
