### ISSUE TITLE
`bdist_rpm` doesn't work because `pyslurm.pyx` isn't included in the source file

### ISSUE THREAD

**Issue by martijnkruiten** [PySlurm/pyslurm#246]
#### Details

* Slurm Version: 22.05.6
* Python Version: 3.6
* Cython Version: 0.29.6
* PySlurm Branch: v22.05.0
* Linux Distribution: Rocky Linux 8.9

#### Issue

`python3 setup.py bdist_rpm` doesn't build and package `pyslurm.cpython-*.so`, which is fixed by manually including `pyslurm/pyslurm.pyx` in the source file (`pyslurm-<version>.tar.bz2`) and building the RPMs with `rpmbuild` directly. I also had to add `-D 'debug_package %{nil}'` to `rpmbuild` to get it to build, but that's a separate issue.

**Comment by tazend** [comment]
Hi,

alright, I can take a look at it and try to get a fix going.

**Comment by tazend** [comment]
@martijnkruiten Could you test it with [this branch](https://github.com/tazend/pyslurm/tree/fix/bdist_rpm)?

**Comment by martijnkruiten** [comment]
Initially it failed, because it tries to build a noarch package with a binary inside, but it works with this command:

```
python3 setup.py bdist_rpm --force-arch=x86_64
```

On my system I did have to change `python-devel` into `python3-devel` in `setup.cfg` and the system Cython is too old (0.28.1 < 0.29.30), so I had to either take the risk and change the requirement, or install a newer version of Cython from somewhere else. That has nothing to do with this issue, though, which is now solved. Thanks a lot!

I'll leave it up to you to close this issue in case you want to keep it open until it's merged.

**Comment by tazend** [comment]
Alright I see, thought it was because I tested it on WSL2 Ubuntu that for some reason it would try to make a noarch package instead of x86_64, but interesting that it's also on your side - not sure why it generates the spec file like that. 

You're right with the python version, it should be `python3-devel`, I'll change that one and then make a pull request
