### ISSUE TITLE
slurmdbd: Rework Job API

### ISSUE THREAD

**Issue by tazend** [PySlurm/pyslurm#269]
## Classes

- [x] `Job` class providing read-only access to all possible members `slurmdb_job_rec_t`
- [x] `Jobs` class, acting as a custom collection (dict) to retrieve actual job-information, and holds all the `Job` instances which carry the information.
- [x] `JobStep` class providing read-only access to all possible members of `slurmdb_job_rec_t` 
- [x] `JobSteps` class, acting as custom collection (dict) to hold all the 'JobStep' instances
- [x] `JobSearchFilter` class acting as a wrapper around `slurmdb_job_cond_t` to search for jobs matching specific conditions.

## General Functionality for a `Job`

- [x] modify

## Other
  
- [x] Documentation
- [x] Write tests
- [x] Write examples

**Comment by multimeric** [comment]
Looks good. I'm also interested in the step statistics, but that can be added later as a subsequent PR if necessary. If you open this as a draft PR and I can review if/when you'd like.

**Comment by tazend** [comment]
Hi @multimeric 

yeah the basic layout for everything is now pretty much done, including [step statistics](https://github.com/PySlurm/pyslurm/blob/rework/db/job-api/pyslurm/core/db/stats.pyx) - just need to parse everything properly now.
I'll let you know when its ready :)

**Comment by multimeric** [comment]
Great! Please open as a draft PR though so it can be reviewed.

**Comment by tazend** [comment]
Done, last missing functionality to modify database Jobs was now added with #297
