### ISSUE TITLE
PySlurm Future and Maintaining the project

### ISSUE THREAD

**Issue by tazend** [PySlurm/pyslurm#278]
Hi @giovtorres @gingergeeks

just wanted to get out some thoughts about the current state of the project.

In general, the current codebase definitely needs a bit of a rework/improvements and especially the documentation and PyPi releases are very much outdated (as mentioned [here](https://github.com/PySlurm/pyslurm/issues/262))

For quite some time I've been working on lots of changes to improve/rework the current API, that I feel like are now finally ready (#224 and almost #269), with I think a solid foundation to also rework other parts of the API more easily and quickly.

However, I am a bit hesitant to merge these changes, mostly because of the uncertainty about the projects future. And especially for the fact that even if the changes were merged, users would not be able to use them properly right
now without documentation. And I believe I do not have the permission to update the documentation on https://pyslurm.github.io/
This has been talked about [here](https://github.com/PySlurm/pyslurm/issues/262) as mentioned, but unfortunately my multiple attempts to reach out about the permission to push documentation/PyPi releases [have not been answered](https://github.com/PySlurm/pyslurm/issues/262#issuecomment-1457950168), which has gotten a bit frustrating lately ;(

With that and realizing that you guys have been inactive for quite some time now within the project, I'd like to ask the following question:

**What do you think about the idea of officially passing on the PySlurm project to me as the new Maintainer?**

As mentioned, I've already spent quite some time on the project and have gathered a lot of experience with the Slurm API itself, and would therefore like to continue to improve/support the project (as it also has become a passion project for me).
I feel like the project is in a state where it definitely needs active development/maintenance, especially to improve the codebase (making it also easier for the community to contribute) and to update the old documentation/pypi releases.

Please let me know what you think about my proposal.

**Comment by gingergeeks** [comment]
@tazend  Move this to a team discussion else PM me ?

**Comment by tazend** [comment]
@gingergeeks yeah I moved it to a team discussion
