### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by gingergeeks** [PySlurm/pyslurm#3]
Have to do this at some point but gradually removing any deprecated usage :
1. Dictionary has_key() calls removed.
2. Dictionary iteritems() calls removed.
3. Unicode strings (in progress).

Completed porting of the following for Py3k support :
1. Updated "**init**.py" so the new absolute import is used via from **future**
2. setup.py minimum requirement is now Python2.6 as that has back ported support for some Py3k enhancements

**Comment by rfehren** [comment]
Hi,

I tried using pyslurm with python 3 but get e.g.:

>>> print(a.find('job_state', 'Running'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 1723, in pyslurm.pyslurm.job.find (pyslurm/pyslurm.c:22792)
TypeError: expected bytes, str found

**Comment by gingergeeks** [comment]
Thanks for that report. I'm currently working on testing 15.08.0-preX so once this working branch is committed (soon) I will take a look to adding proper Python3 support to it as well.

**Comment by gingergeeks** [comment]
Having had a play it looks like I will need to commit current 15.08.0-preX branch (Python2.x) and start making changes for Python3 after that. Which Slurm version are you using ?

**Comment by rfehren** [comment]
I'm using 14.11.5. As I said, we're happy to help porting.

**Comment by MikeDacre** [comment]
I am working on getting this working with python3 now, I fixed @rfehren problem by changing 
    def find(self, char *name='', val=''):
to 
    def find(self, name='', val='')

This works as expected in both python2 and python3, plus I think it makes more sense than making the round trip to C, which seems unnecessary and potentially costly in this instance.

I could be wrong though, I am not a C programmer (anymore) and I rarely use cython. Thoughts?

**Comment by MikeDacre** [comment]
I just made a pull request for the 14.11.5 branch that applies this fix

**Comment by giovtorres** [comment]
PR #87 added python3 compatibility to PySlurm.  If there are any lingering encoding issues in Python3, please raise a new, specific issue for it.  Thanks.
