### ISSUE TITLE
Node in Nodes collection do not report a MIXED state, only IDLE or ALLOCATED

### ISSUE THREAD

**Issue by tazend** [PySlurm/pyslurm#317]
### Discussed in https://github.com/orgs/PySlurm/discussions/316

<div type='discussions-op-text'>

<sup>Originally posted by **robgics** August 25, 2023</sup>
I used the collection to load all nodes, and then I print out the state of all of them.  They are all either IDLE, ALLOCATED, or some form of DOWN/DRAIN...but no MIXED.   Inspecting particular nodes that I know are mixed (via scontrol show node) shows that if a node is MIXED (so even 1 cpu in use, out of 48), then it will appear as ALLOCATED via pyslurm.

I *think* we can work around this by comparing total cpus and allocated cpus.  But I'm just wondering if this simplification is intentional or if I'm missing something.  

Thanks!

</div>

**Comment by tazend** [comment]
mh, that is weird. Because I'm using the exact same function that scontrol is also using, and they just print the result of that function out.
I'll have to test that out on my Cluster.

**Comment by tazend** [comment]
@robgics 

also found the error in this case - will make the fix tomorrow together with #315.
Thank you for spotting all the bugs :)

**Comment by robgics** [comment]
Heh, that's been the easy part for me.  It's been being SURE it's a bug and not just a mistake I'm making that's been the hard part.  Thanks for being so responsive.  You fixed those bugs before I was able to make a dent in understanding the deeper workings of pyslurm.

**Comment by tazend** [comment]
Alright, fixed now in `main`, same with #315
