### ISSUE TITLE
error: ‘KILL_JOB_ARRAY’ undeclared

### ISSUE THREAD

**Issue by btravouillon** [PySlurm/pyslurm#324]
#### Details

* Slurm Version: 23.02.6
* Python Version: 3.7.3
* Cython Version: 0.29.14
* PySlurm Branch: v23.2.2
* Linux Distribution: Debian 10 buster

#### Issue

The installation fails with:
```
      pyslurm/pyslurm.c:90547:40: error: ‘KILL_JOB_ARRAY’ undeclared (first use in this function); did you mean ‘KILL_JOB_RESV’?
         __pyx_t_2 = __Pyx_PyInt_From_uint8_t(KILL_JOB_ARRAY); if (unlikely(!__pyx_t_2)) __PYX_ERR(7, 412, __pyx_L1_error)
                                              ^~~~~~~~~~~~~~
                                              KILL_JOB_RESV
      pyslurm/pyslurm.c:90547:40: note: each undeclared identifier is reported only once for each function it appears in
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

This is related to this change in Slurm: [Rename KILL_JOB_ARRAY to KILL_ARRAY_TASK](https://github.com/SchedMD/slurm/commit/987557a26e547978cfe795d14d9887c4854008ae)

The build completes with this patch: https://github.com/PySlurm/pyslurm/compare/main...btravouillon:pyslurm:fix/KILL_JOB_ARRAY_not_found

I can open a PR if requested.

**Comment by tazend** [comment]
Hi @btravouillon 

sure you can do a PR for this. However, instead of renaming it, you can just delete these two lines. They are not used anywhere in the code so that is fine
