### ISSUE TITLE
Slurm 23.11 support

### ISSUE THREAD

**Issue by martijnkruiten** [PySlurm/pyslurm#327]
Slurm 23.11 has been released and PySlurm needs some changes beyond just changing the version number to be compatible with it.

**Comment by tazend** [comment]
Hi @martijnkruiten 

currently working on it. (On this branch: https://github.com/tazend/pyslurm/tree/23.11.x)

Got a working version that compiles and passes all unit-tests - compiling without contents of `pyslurm/pyslurm.pyx` at the moment though, that file needs a bit more treatment. Will try to look into it in the following days.

**Comment by tazend** [comment]
Hi,

took a bit longer than expected - but here is the new release for 23.11: 

https://github.com/PySlurm/pyslurm/releases/tag/v23.11.0

**Comment by martijnkruiten** [comment]
Thanks, it's very much appreciated!
