### ISSUE TITLE
Support for 24.05.3

### ISSUE THREAD

**Issue by sanxing-chen** [PySlurm/pyslurm#346]
Is there any plan for 24.05.3 support?

Thanks!

**Comment by tazend** [comment]
Hi,

24.05 is now supported - you can either use the `main` branch, or this one: https://github.com/PySlurm/pyslurm/tree/24.5.x

**Comment by osnyx** [comment]
Hey @tazend, thank you for implementing support for the more recent slurm release. Do you plan to cut an official release of this package soon?
Asking as a distro packager to decide on whether to package just an intermediate commit or not.

**Comment by tazend** [comment]
Hi @osnyx 

sorry for taking so long, I just published a new release now.
