### ISSUE TITLE
Support for Slurm 24.11.x

### ISSUE THREAD

**Issue by tazend** [PySlurm/pyslurm#354]
Already working on it

**Comment by tazend** [comment]
support for 24.11.x added with #361

**Comment by walterdejong** [comment]
Tested this from your fork just this morning, nice work.

One remark, `pyslurm.version()` was removed. We can live with `pyslurm.__version__`, that's okay.

**Comment by tazend** [comment]
Hi @walterdejong,

thanks for the feedback.
Yeah I removed pyslurm.version() because it seemed rendundant since one can rely on __version__ directly. Perhaps it is a bit uglier now though, apoligies for that - maybe it was not the most necessary change anyway :)
