### ISSUE TITLE
job=pyslurm.job().find_id(job_id)[0] raise an error "an integer is required"

### ISSUE THREAD

**Issue by thefivespace** [PySlurm/pyslurm#357]
#### Details

* Slurm Version:latest
* Python Version:3.9
* Cython Version: latest
* PySlurm Branch:latest
* Linux Distribution: rocky

**Comment by tazend** [comment]
Hi,

the `pyslurm.job` API is deprecated.
Please use the `pyslurm.Job` class instead: https://pyslurm.github.io/23.2/reference/job/

(will update the documentation for 24.5 soon, but its basically the same)

**Comment by thefivespace** [comment]
3Q
