### ISSUE TITLE
node().get() breaks on hidden nodes

### ISSUE THREAD

**Issue by mstud** [PySlurm/pyslurm#69]
Due to the
   if record.name is NULL:
      break
in pyslurm.pyx line 2609+, PySlurm fails to fetch the remaining node data as soon as it encounters a node that is in a hidden partition. A "continue" instead of the "break" would be better.
Alternatively, one could think about changing _ShowFlags to include SHOW_ALL for the node class, so that nodes in hidden partitions will be reported normally and their record.name won't be NULL anymore.

**Comment by giovtorres** [comment]
Hi.  Thanks for reporting and troubleshooting.  I'll have a look at this shortly.  Your proposed changes seem quite reasonable.

**Comment by giovtorres** [comment]
Fixed in d14f816

**Comment by giovtorres** [comment]
Let me know if this is OK for you now.  Thanks.

**Comment by mstud** [comment]
Yes, work's perfectly now. Thanks.
