### ISSUE TITLE
could not build pyslurm against latest slurm 

### ISSUE THREAD

**Issue by jsalinasintel** [PySlurm/pyslurm#75]
I just installed slurm to /usr/local: 
-rwxr-xr-x 1 root root 3605314 Nov 21 21:53 /usr/local/bin/sacct
-rwxr-xr-x 1 root root 3921674 Nov 21 21:53 /usr/local/bin/sacctmgr
-rwxr-xr-x 1 root root 3544833 Nov 21 21:53 /usr/local/bin/salloc
-rwxr-xr-x 1 root root 3498011 Nov 21 21:53 /usr/local/bin/sattach
-rwxr-xr-x 1 root root 3565686 Nov 21 21:53 /usr/local/bin/sbatch
-rwxr-xr-x 1 root root 3486240 Nov 21 21:53 /usr/local/bin/sbcast
-rwxr-xr-x 1 root root 3512420 Nov 21 21:53 /usr/local/bin/scancel
-rwxr-xr-x 1 root root 3683536 Nov 21 21:53 /usr/local/bin/scontrol
-rwxr-xr-x 1 root root 3479103 Nov 21 21:53 /usr/local/bin/sdiag
-rwxr-xr-x 1 root root 3580814 Nov 21 21:53 /usr/local/bin/sinfo
-rwxr-xr-x 1 root root 3506942 Nov 21 21:53 /usr/local/bin/sprio
-rwxr-xr-x 1 root root 3615467 Nov 21 21:53 /usr/local/bin/squeue
-rwxr-xr-x 1 root root 3648488 Nov 21 21:53 /usr/local/bin/sreport
-rwxr-xr-x 1 root root 3495982 Nov 21 21:53 /usr/local/bin/sshare
-rwxr-xr-x 1 root root 3509465 Nov 21 21:53 /usr/local/bin/sstat
-rwxr-xr-x 1 root root 3493655 Nov 21 21:53 /usr/local/bin/strigger
-rwxr-xr-x 1 root root 3680324 Nov 21 21:53 /usr/local/bin/srun

Setup is pointed to /usr/local but it fails 

# python setup.py build 
INFO:root:Info: 
INFO:root:Info: Building PySlurm (16.05.5)
INFO:root:Info: ------------------------------
INFO:root:Info: 
INFO:root:Info: Cython version 0.19 installed

INFO:root:Info: Clean - checking for objects to clean
INFO:root:Info: Clean - completed
INFO:root:Info: Build - Detected Slurm include file version - 0x100506 (16.05.06)
INFO:root:Info: Build - Writing Slurm version to pyslurm/slurm_version.pxi
INFO:root:Info: Build - Generating pyslurm/bluegene.pxi file
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pyslurm
copying pyslurm/__init__.py -> build/lib.linux-x86_64-2.7/pyslurm
running build_ext
Traceback (most recent call last):
  File "setup.py", line 323, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 163, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 170, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 181, in cython_sources
    from Cython.Compiler.Main \
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Main.py", line 19, in <module>
    from Symtab import ModuleScope
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Symtab.py", line 10, in <module>
    import PyrexTypes
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/PyrexTypes.py", line 5, in <module>
    from Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
  File "Code.py", line 705, in init Cython.Compiler.Code (/builddir/build/BUILD/Cython-0.19/Cython/Compiler/Code.c:56136)
  File "/usr/local/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression

**Comment by giovtorres** [comment]
What version of Slurm are you running?  Also, looks like you are running Cython 0.19 and Python 2.7?  How are you invoking `python setup.py build`?  What is the path to slurm.h?  Is it */usr/local/include/slurm*?

**Comment by giovtorres** [comment]
I just spun up a local Slurm cluster running 16.05.6, Cython 0.19 and Python 2.7 in a clean environment. I compiled slurm with `--prefix=/usr/local` to mimic your setup.  I then cloned pyslurm and ran `python setup.py build --slurm=/usr/local && python setup.py install` as root.  It compiled fine and is working.

Not sure why it is failing.  I'll wait to get more details from you.

**Comment by jsalinasintel** [comment]
Greetings!  I just downloaded the latest stable slurm today: slurm-16.05.6.   It is installed to /usr/local.  
Python: # python --version 
Python 2.7.11 
And Cython 0.19 

I just cloned pyslurm today as well it should be the latest: 
[root@soak-40 pyslurm]# setup.py build --slurm=/usr/local
-bash: setup.py: command not found
[root@soak-40 pyslurm]# python setup.py build --slurm=/usr/local
INFO:root:Info: 
INFO:root:Info: Building PySlurm (16.05.5)
INFO:root:Info: ------------------------------
INFO:root:Info: 
INFO:root:Info: Cython version 0.19 installed

INFO:root:Info: Clean - checking for objects to clean
INFO:root:Info: Clean - removing pyslurm build temp directory ...
INFO:root:Info: Clean - removing pyslurm/bluegene.pxi temp file
INFO:root:Info: Clean - removing pyslurm/slurm_version.pxi temp file
INFO:root:Info: Clean - completed
INFO:root:Info: Build - Detected Slurm include file version - 0x100506 (16.05.06)
INFO:root:Info: Build - Writing Slurm version to pyslurm/slurm_version.pxi
INFO:root:Info: Build - Generating pyslurm/bluegene.pxi file
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pyslurm
copying pyslurm/__init__.py -> build/lib.linux-x86_64-2.7/pyslurm
running build_ext
Traceback (most recent call last):
  File "setup.py", line 323, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 163, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 170, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 181, in cython_sources
    from Cython.Compiler.Main \
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Main.py", line 19, in <module>
    from Symtab import ModuleScope
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Symtab.py", line 10, in <module>
    import PyrexTypes
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/PyrexTypes.py", line 5, in <module>
    from Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
  File "Code.py", line 705, in init Cython.Compiler.Code (/builddir/build/BUILD/Cython-0.19/Cython/Compiler/Code.c:56136)
  File "/usr/local/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression

Looks like this is: 
    if isinstance(pattern, _pattern_type):
        if flags:
            raise ValueError('Cannot process flags argument with a compiled pattern')
        return pattern
    if not sre_compile.isstring(pattern):
        raise TypeError, "first argument must be string or compiled pattern"
    try:
        p = sre_compile.compile(pattern, flags)
    except error, v:
        raise error, v # invalid expression

I didn't have to install cython as it was already installed so when I did pip install it said the requirement was already satisified.  Might I need to do anything around that?

**Comment by giovtorres** [comment]
I haven't come across this error before.  PySlurm works with Cython 0.19.  Is this CentOS 7?
Is it possible setup.py was edited?  Could you run `git status` in the repo and make sure there are no changes to setup.py?

**Comment by giovtorres** [comment]
You could also try a newer version of Cython just to be sure, but its hard to say if it will fix this problem.

**Comment by jsalinasintel** [comment]
# wget https://github.com/PySlurm/pyslurm/archive/master.zip 
--2016-11-30 22:55:46--  https://github.com/PySlurm/pyslurm/archive/master.zip
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/PySlurm/pyslurm/zip/master [following]
--2016-11-30 22:55:47--  https://codeload.github.com/PySlurm/pyslurm/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘master.zip’

    [   <=>                                                                                                                         ] 331,124      570KB/s   in 0.6s   
2016-11-30 22:55:48 (570 KB/s) - ‘master.zip’ saved [331124]

# md5sum master.zip 
d2a2b18225b1374ee058dacfc1a62ea3  master.zip

[root@soak-40 pyslurm-master]# which python 
/usr/local/bin/python
[root@soak-40 pyslurm-master]# export PYTHONPATH=/usr/lib64/python2.7/site-packages 
[root@soak-40 pyslurm-master]# python setup.py build --slurm=/usr/local
INFO:root:Info: 
INFO:root:Info: Building PySlurm (16.05.5)
INFO:root:Info: ------------------------------
INFO:root:Info: 
INFO:root:Info: Cython version 0.19 installed

INFO:root:Info: Clean - checking for objects to clean
INFO:root:Info: Clean - completed
INFO:root:Info: Build - Detected Slurm include file version - 0x100506 (16.05.06)
INFO:root:Info: Build - Writing Slurm version to pyslurm/slurm_version.pxi
INFO:root:Info: Build - Generating pyslurm/bluegene.pxi file
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pyslurm
copying pyslurm/__init__.py -> build/lib.linux-x86_64-2.7/pyslurm
running build_ext
Traceback (most recent call last):
  File "setup.py", line 323, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 163, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 170, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 181, in cython_sources
    from Cython.Compiler.Main \
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Main.py", line 19, in <module>
    from Symtab import ModuleScope
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Symtab.py", line 10, in <module>
    import PyrexTypes
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/PyrexTypes.py", line 5, in <module>
    from Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
  File "Code.py", line 705, in init Cython.Compiler.Code (/builddir/build/BUILD/Cython-0.19/Cython/Compiler/Code.c:56136)
  File "/usr/local/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression 


with -d 
# python -d setup.py build --slurm=/usr/local
INFO:root:Info: 
INFO:root:Info: Building PySlurm (16.05.5)
INFO:root:Info: ------------------------------
INFO:root:Info: 
INFO:root:Info: Cython version 0.19 installed

INFO:root:Info: Clean - checking for objects to clean
INFO:root:Info: Clean - removing pyslurm build temp directory ...
INFO:root:Info: Clean - removing pyslurm/bluegene.pxi temp file
INFO:root:Info: Clean - removing pyslurm/slurm_version.pxi temp file
INFO:root:Info: Clean - completed
INFO:root:Info: Build - Detected Slurm include file version - 0x100506 (16.05.06)
INFO:root:Info: Build - Writing Slurm version to pyslurm/slurm_version.pxi
INFO:root:Info: Build - Generating pyslurm/bluegene.pxi file
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pyslurm
copying pyslurm/__init__.py -> build/lib.linux-x86_64-2.7/pyslurm
running build_ext
Traceback (most recent call last):
  File "setup.py", line 323, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 163, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 170, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/usr/lib64/python2.7/site-packages/Cython/Distutils/build_ext.py", line 181, in cython_sources
    from Cython.Compiler.Main \
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Main.py", line 19, in <module>
    from Symtab import ModuleScope
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Symtab.py", line 10, in <module>
    import PyrexTypes
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/PyrexTypes.py", line 5, in <module>
    from Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
  File "Code.py", line 705, in init Cython.Compiler.Code (/builddir/build/BUILD/Cython-0.19/Cython/Compiler/Code.c:56136)
  File "/usr/local/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression

**Comment by jsalinasintel** [comment]
CentOS Linux release 7.2.1511 (Core) 
cpe:/o:centos:centos:7

**Comment by jsalinasintel** [comment]
python-pyudev-0.15-7.el7_2.1.noarch
python-slip-dbus-0.4.0-2.el7.noarch
python-sssdconfig-1.13.0-40.el7_2.12.noarch
python-sss-murmur-1.13.0-40.el7_2.12.x86_64
python-cffi-0.8.6-2.el7.x86_64
python-setuptools-0.9.8-4.el7.noarch
dbus-python-1.1.1-9.el7.x86_64
python-slip-0.4.0-2.el7.noarch
python-iniparse-0.4-9.el7.noarch
python-perf-3.10.0-327.28.3.el7.x86_64
python-pycurl-7.19.0-17.el7.x86_64
python-libs-2.7.5-38.el7_2.x86_64
python-pyasn1-0.1.6-2.el7.noarch
python-six-1.9.0-2.el7.noarch
python-libipa_hbac-1.13.0-40.el7_2.12.x86_64
python-netaddr-0.7.5-7.el7.noarch
python-enum34-1.0.4-1.el7.noarch
python-yubico-1.2.3-1.el7.noarch
python-dateutil-1.5-7.el7.noarch
python-nss-0.16.0-3.el7.x86_64
python-pycparser-2.14-1.el7.noarch
python-cryptography-0.8.2-1.el7.x86_64
python-kerberos-1.1-15.el7.x86_64
python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
ipa-python-4.2.0-15.0.1.el7.centos.18.x86_64
python-pip-7.1.0-1.el7.noarch
libselinux-python-2.2.2-6.el7.x86_64
python-configobj-4.7.2-7.el7.noarch
newt-python-0.52.15-4.el7.x86_64
python-urlgrabber-3.10-7.el7.noarch
python-qrcode-core-5.0.1-1.el7.noarch
rpm-python-4.11.3-17.el7.x86_64
python-lxml-3.2.1-4.el7.x86_64
python-krbV-1.0.90-8.el7.x86_64
python-dns-1.12.0-1.20150617git465785f.el7.noarch
python-ldap-2.4.15-2.el7.x86_64
python-ply-3.4-10.el7.noarch
python-backports-1.0-8.el7.x86_64
python2-configargparse-0.10.0-1.el7.noarch
python-2.7.5-38.el7_2.x86_64
python-decorator-3.4.0-3.el7.noarch

**Comment by giovtorres** [comment]
Could you try with a newer version of Cython?

**Comment by jsalinasintel** [comment]
Hmm not sure what this means: # pip install --upgrade Cython
Collecting Cython
  Downloading Cython-0.25.1-cp27-cp27mu-manylinux1_x86_64.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 147kB/s 
Installing collected packages: Cython
  Found existing installation: Cython 0.19
    DEPRECATION: Uninstalling a distutils installed project (Cython) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling Cython-0.19:
      Successfully uninstalled Cython-0.19
Successfully installed Cython-0.25.1
[root@soak-40 pyslurm-master]# python -d setup.py build --slurm=/usr/local
INFO:root:Info: 
INFO:root:Info: Building PySlurm (16.05.5)
INFO:root:Info: ------------------------------
INFO:root:Info: 
INFO:root:Info: Cython version 0.25.1 installed

INFO:root:Info: Clean - checking for objects to clean
INFO:root:Info: Clean - removing pyslurm build temp directory ...
INFO:root:Info: Clean - removing pyslurm/bluegene.pxi temp file
INFO:root:Info: Clean - removing pyslurm/slurm_version.pxi temp file
INFO:root:Info: Clean - completed
INFO:root:Info: Build - Detected Slurm include file version - 0x100506 (16.05.06)
INFO:root:Info: Build - Writing Slurm version to pyslurm/slurm_version.pxi
INFO:root:Info: Build - Generating pyslurm/bluegene.pxi file
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pyslurm
copying pyslurm/__init__.py -> build/lib.linux-x86_64-2.7/pyslurm
running build_ext
failed to import Cython: /usr/lib64/python2.7/site-packages/Cython/Compiler/Scanning.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
error: Cython does not appear to be installed
 
# /usr/local/bin/python2.7 -d setup.py build --slurm=/usr/local
INFO:root:Info: 
INFO:root:Info: Building PySlurm (16.05.5)
INFO:root:Info: ------------------------------
INFO:root:Info: 
INFO:root:Info: Cython version 0.25.1 installed

INFO:root:Info: Clean - checking for objects to clean
INFO:root:Info: Clean - removing pyslurm build temp directory ...
INFO:root:Info: Clean - removing pyslurm/bluegene.pxi temp file
INFO:root:Info: Clean - removing pyslurm/slurm_version.pxi temp file
INFO:root:Info: Clean - completed
INFO:root:Info: Build - Detected Slurm include file version - 0x100506 (16.05.06)
INFO:root:Info: Build - Writing Slurm version to pyslurm/slurm_version.pxi
INFO:root:Info: Build - Generating pyslurm/bluegene.pxi file
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pyslurm
copying pyslurm/__init__.py -> build/lib.linux-x86_64-2.7/pyslurm
running build_ext
failed to import Cython: /usr/lib64/python2.7/site-packages/Cython/Compiler/Scanning.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
error: Cython does not appear to be installed
 
I will look at why it is not finding cython after upgrade tomorrow

**Comment by jsalinasintel** [comment]
maybe I should just install my own python

**Comment by giovtorres** [comment]
I previously built pyslurm in a Docker container on the same platform as you (CentOS 7, Python 2.7 and Cython 0.19) and couldn't replicate your issue.

I just build a CentOS 7 virtual machine, installed slurm and built PySlurm and still couldn't replicate.  I'm afraid something is amiss on your system.

**Comment by jsalinasintel** [comment]
I haven't seen anything that would cause me to disagree with you  -- this is a physical host (which I would think would be easier)

**Comment by giovtorres** [comment]
Here's my history if it helps:

```
    1  yum install epel-release
    2  yum -y install wget bzip2 perl gcc vim-enhanced git make munge munge-devel python-devel python-pip

    4  yum install Cython
    5  groupadd -r slurm && useradd -r -g slurm slurm
    6  wget http://www.schedmd.com/download/latest/slurm-16.05.6.tar.bz2

    9  mkdir /usr/local/src/slurm

   11  tar jxf slurm-16.05.6.tar.bz2 -C /usr/local/src/slurm/ --strip-components=1
   12  cd /usr/local/src/slurm/

   14  ./configure --enable-debug --enable-front-end --prefix=/usr --sysconfdir=/etc/slurm     && make install     && install -D -m644 etc/cgroup.conf.example /etc/slurm/cgroup.conf.example     && install -D -m644 etc/slurm.conf.example /etc/slurm/slurm.conf.example     && install -D -m644 etc/slurm.epilog.clean /etc/slurm/slurm.epilog.clean     && install -D -m644 etc/slurmdbd.conf.example /etc/slurm/slurmdbd.conf.example     && cd     && rm -rf /usr/local/src/slurm     && mkdir /etc/sysconfig/slurm     && mkdir /var/spool/slurmd     && chown slurm:slurm /var/spool/slurmd     && mkdir /var/run/slurmd     && chown slurm:slurm /var/run/slurmd     && mkdir /var/lib/slurmd     && chown slurm:slurm /var/lib/slurmd     && /sbin/create-munge-key
   15  vim /etc/slurm/slurm.conf

   20  systemctl start munge.service

   23  slurmctld -D -vvvv &
   24  slurmd -D -vvvv
   25  git clone https://github.com/pyslurm/pyslurm.git
   26  cd pyslurm/
   27  python setup.py build 
   28  python setup.py install
```

It's certainly not a production setup, but enough for me to do PySlurm development.

**Comment by giovtorres** [comment]
any luck?
