### ISSUE TITLE
working with SLURM database

### ISSUE THREAD

**Issue by hpourreza** [PySlurm/pyslurm#76]
It would be nice to add methods to work with SLURM database. For example, to get list of jobs submitted by a user, or get the core hours used by an account during a period of time. 

I currently use `sacct -A account_name -a --starttime=xxx --format=cputimeRaw` to get CPU seconds and divide that by 3600 to get core hours used by an account.

**Comment by gingergeeks** [comment]
Hi there @hpourreza, we are currently looking at this request so please bear with us.

**Comment by giovtorres** [comment]
There is now some slurmdb support in `master` and the `18.08.0` branches.  If anything specific or not working there, please open another issue.  Thanks.
