### ISSUE TITLE
When slurm is installed in a different location, 'lib64' look up fails

### ISSUE THREAD

**Issue by akhi3030** [PySlurm/pyslurm#77]
We have installed slurm in a different location so when I run setup.py something like below:

python setup.py build --slurm=...

My slurm libraries are not present in 'lib' but in 'lib64'.  I found that I had to make the following change to get setup.py to get it to pick it up properly.

diff -u pyslurm-master/setup.py pyslurm-master1/setup.py
--- pyslurm-master/setup.py     2016-12-08 17:20:26.000000000 -0800
+++ pyslurm-master1/setup.py    2016-12-13 03:08:11.197188595 -0800
@@ -251,7 +251,7 @@
 
     if not os.path.exists("%s/libslurm.so" % SLURM_LIB):
         info("Build - Cannot locate the Slurm shared library in %s, checking lib64 .... " % SLURM_LIB)
-        SLURM_LIB = "%s/lib64" %  DEFAULT_SLURM
+        SLURM_LIB = os.path.abspath(os.path.join(SLURM_LIB, '..', 'lib64'))

**Comment by giovtorres** [comment]
Thanks for reporting.  What prefix did you use when building Slurm?

**Comment by akhi3030** [comment]
Neither.  I was running just "python setup.py build --slurm=...".  I first tried running "python setup.py build".  When that failed to find the slurm installation, the error msg suggested that I specify --slurm.  So I tried "python setup.py build --slurm=...".  That failed so I started inspecting setup.py.

**Comment by giovtorres** [comment]
In your case, the slurm libraries are not installed in the default lib directory, **[EPREFIX]/lib**.  Therefore, you should not use PySlurm's `--slurm` flag when building.  Instead, use the `--slurm-lib` and `--slurm-inc` build flags together.

For example, if slurm was built like this `./configure --prefix=/usr/local/slurm --libdir=/usr/local/slurm/lib64`, then you would build PySlurm as follows:  `python setup.py build --slurm-lib=/usr/local/slurm/lib64 --slurm-inc=/usr/local/slurm/include`.  This way, PySlurm will find libslurm and continue with the build.

**Comment by akhi3030** [comment]
Makes sense.  I guess I was confused because the error message did not mention slurm-lib and slurm-inc but just slurm.  However, looking through setup.py, you can easily see that it is possible to set slurm-lib and slurm-inc.  

So maybe the error message could be improved slightly.  Otherwise, I think this issue is invalid.
