### ISSUE TITLE
Python 3.5 and/or 3.6?

### ISSUE THREAD

**Issue by cclauss** [PySlurm/pyslurm#90]
Why stop at Python 3.4?

**Comment by giovtorres** [comment]
It was more of a start than a stop.  Ideally, we would like to support Python 3.3+.  Python 3.4 is available through the EPEL 7 repo, so it was the easiest to add into the build/test container.  Now that Python3 compatibility seems to be ok, I'll look at adding other versions of Py3 either by installing from source and using something like Lmod to switch between versions, or using the a third-party repo like IUS for getting later versions of Python installed.

**Comment by cclauss** [comment]
Python 3.3 goes EOL this month https://docs.python.org/devguide/index.html#branchstatus so I doubt that going back to 3.3 helps.

**Comment by giovtorres** [comment]
I didn't realize EOL for 3.3 was so close.  3.4+ it is!
