### ISSUE TITLE
Compiling on Ubuntu

### ISSUE THREAD

**Issue by dendisuhubdy** [PySlurm/pyslurm#93]
After a couple of installing errors, here's some suggestion to complete compilation on Ubuntu 14.04

build slurm 17.02 first 
```
git clone git@github.com:SchedMD/slurm.git
cd slurm
git checkout slurm-17.02
.configure --prefix=~/.local/
make
make install 
```

```
git clone git@github.com:PySlurm/pyslurm.git
cd pyslurm
python setup.py build --slurm=~/.local/
python setup.py install
``` 

it finally works for me

**Comment by giovtorres** [comment]
Thanks.  The `--slurm` flag is covered in step 3 of the **Installation** section of the README.

```
3. Slurm root directory (Alternate installation directory):

        python setup.py build --slurm=PATH_TO_SLURM_DIR
```

Did you have other issues building PySlurm on Ubuntu?

**Comment by dendisuhubdy** [comment]
No, not that I know of, but I'm trying to run the examples and it shows up this error of `python: error: s_p_parse_file: unable to status file /u/$USER/.local/etc/slurm.conf: No such file or directory, retrying in 1sec up to 60sec` although I'm in a Slurm environment.

**Comment by giovtorres** [comment]
Which example script did that message come from?  The error indicates it can't find your local `slurm.conf`.
